name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Build binaries
      run: |
        # Create dist directory
        mkdir -p dist
        
        # Build for multiple platforms
        GOOS=linux GOARCH=amd64 go build -o dist/md_split-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o dist/md_split-linux-arm64 .
        GOOS=darwin GOARCH=amd64 go build -o dist/md_split-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -o dist/md_split-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -o dist/md_split-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -o dist/md_split-windows-arm64.exe .

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}